Meteor.startup(function () {  
  Hexes._ensureIndex({x:1, y:1}, {unique:1})
  Castles._ensureIndex({user_id:1, x:1, y:1})
  Villages._ensureIndex({user_id:1, x:1, y:1})
  Armies._ensureIndex({x:1, y:1})
  Jobstats._ensureIndex({job_name:1})
  Notifications._ensureIndex({user_id:1, type:1})
  Battles._ensureIndex({x:1, y:1})
  Chats._ensureIndex({room_id:1})
  Dailystats._ensureIndex({user_id:1})
  Threads._ensureIndex({forum_id:1})
  Messages._ensureIndex({thread_id:1})
  Latestchats._ensureIndex({room_id:1})
  Moves._ensureIndex({army_id:1})
})