Meteor.startup(function () {
    Hexbakes._ensureIndex({centerX:1, centerY:1, hasCoords:1})
    Hexes._ensureIndex({x:1, y:1}, {unique:1})
    Castles._ensureIndex({user_id:1, x:1, y:1})
    Villages._ensureIndex({user_id:1, x:1, y:1})
    Armies._ensureIndex({x:1, y:1})
    Moves._ensureIndex({army_id:1, user_id:1})
    Battles._ensureIndex({x:1, y:1, isOver:1})
    Fights._ensureIndex({battle_id:1})
    Settings._ensureIndex({name:1})
    Rooms._ensureIndex({members:1, type:1})
    Roomchats._ensureIndex({room_id:1})
    Threads._ensureIndex({forum_id:1})
    Messages._ensureIndex({thread_id:1})
    Dailystats._ensureIndex({user_id:1})
    Alerts._ensureIndex({"user_ids.user_id":1})
})
