#!/bin/bash

i=0

result[$i]=~/meteor/gridgame/public/game_images/army_01.png
all[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/army_01_all/render.png
ao[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/army_01_ao/render.png
((i++))

result[$i]=~/meteor/gridgame/public/game_images/hex_wool_01.png
all[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/wool_01_all/render.png
ao[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/wool_01_ao/render.png
((i++))

result[$i]=~/meteor/gridgame/public/game_images/hex_glass_01.png
all[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/glass_01_all/render.png
ao[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/glass_01_ao/render.png
((i++))

result[$i]=~/meteor/gridgame/public/game_images/castle_01.png
all[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/castle_01_all/render.png
ao[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/castle_01_ao/render.png
((i++))

result[$i]=~/meteor/gridgame/public/game_images/castle_02_keep.png
all[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/castle_02_keep_all/render.png
ao[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/castle_02_keep_ao/render.png
((i++))

result[$i]=~/meteor/gridgame/public/game_images/castle_03_skull.png
all[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/castle_03_skull_all/render.png
ao[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/castle_03_skull_ao/render.png
((i++))

result[$i]=~/meteor/gridgame/public/game_images/castle_04_arabian.png
all[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/castle_04_arabian_all/render.png
ao[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/castle_04_arabian_ao/render.png
((i++))

result[$i]=~/meteor/gridgame/public/game_images/castle_05_waterfall.png
all[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/castle_05_waterfall_all/render.png
ao[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/castle_05_waterfall_ao/render.png
((i++))

result[$i]=~/meteor/gridgame/public/game_images/village_01.png
all[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/village_01_all/render.png
ao[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/village_01_ao/render.png
((i++))

result[$i]=~/meteor/gridgame/public/game_images/hex_grain_01.png
all[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/grain_01_all/render.png
ao[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/grain_01_ao/render.png
((i++))

result[$i]=~/meteor/gridgame/public/game_images/hex_grain_02.png
all[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/grain_02_all/render.png
ao[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/grain_02_ao/render.png
((i++))

result[$i]=~/meteor/gridgame/public/game_images/hex_grain_03.png
all[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/grain_03_all/render.png
ao[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/grain_03_ao/render.png
((i++))

result[$i]=~/meteor/gridgame/public/game_images/hex_lumber_01.png
all[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/lumber_01_all/render.png
ao[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/lumber_01_ao/render.png
((i++))

result[$i]=~/meteor/gridgame/public/game_images/hex_ore_01.png
all[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/ore_01_all/render.png
ao[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/ore_01_ao/render.png
((i++))

result[$i]=~/meteor/gridgame/public/game_images/hex_clay_01.png
all[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/clay_01_all/render.png
ao[$i]=/media/dan/166868D86868B85F/Users/danph_000/Documents/maya/projects/default/images/clay_01_ao/render.png


echo ""
echo "processing images"
for index in ${!all[*]}
do
    printf "%4d: %s\n" $index ${result[$index]}

    convert ${ao[$index]} +level 50%,100% ../.temp/temp_ao_lightened.png
    composite ${all[index]} -compose Multiply ../.temp/temp_ao_lightened.png ${result[$index]}
done

echo "done processing images"
echo ""
